# Exported from Render on 2025-03-11T02:57:59Z
services:
- type: web
  name: 100minds-backend
  runtime: node
  repo: https://github.com/100-Minds/backend
  plan: free
  envVars:
  - key: R2_PUBLIC_URL
    sync: false
  - key: R2_CDN_URL
    sync: false
  - key: R2_BUCKET_NAME
    sync: false
  - key: R2_SECRET_ACCESS_KEY
    sync: false
  - key: R2_ACCESS_KEY_ID
    sync: false
  - key: R2_TOKEN_VALUE
    sync: false
  - key: R2_REGION
    sync: false
  - key: R2_ACCOUNT_ID
    sync: false
  - key: GMAIL_PASSWORD
    sync: false
  - key: GMAIL_USER
    sync: false
  - key: QUEUE_REDIS_PORT
    sync: false
  - key: QUEUE_REDIS_PASSWORD
    sync: false
  - key: QUEUE_REDIS_URL
    sync: false
  - key: FRONTEND_URL
    sync: false
  - key: REFRESH_TOKEN_EXPIRES_IN
    sync: false
  - key: ACCESS_TOKEN_EXPIRES_IN
    sync: false
  - key: REFRESH_TOKEN
    sync: false
  - key: ACCESS_TOKEN
    sync: false
  - key: AUTH_SECRET
    sync: false
  - key: DB_DATABASE
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_HOST
    sync: false
  - key: DB_PORT
    sync: false
  - key: NODE_ENV
    sync: false
  - key: APP_PORT
    sync: false
  - key: APP_NAME
    sync: false
  region: frankfurt
  buildCommand: npm install && npm run build
  startCommand: npm run start-prod
version: "1"
